### ISSUE TITLE
Problem when enabling building option: "EUDAQ BUILD STDEVENT MONITOR=ON" during installation

### ISSUE THREAD

**Issue by km-b214** [eudaq/eudaq#649] opened 2022-01-28 04:00 UTC
Hello, 

I have a problem during "make install" after I enable the building option: EUDAQ BUILD STDEVENT MONITOR=ON. Running "make install" with default setting directed from the manual is fine. Here is the error message: 

![image](https://user-images.githubusercontent.com/81219506/151484707-ee271d5b-391c-48db-9b97-991a37cb1711.png)

I wonder if anyone could help me with this. 

Thank you,

**Comment by lhuth** [comment] 2022-01-28 11:53
Hi @km-b214 ,

We have not observed this error yet. It stems from root. Which exact version of root are you using?
Cheers,

@lhuth

**Comment by km-b214** [comment] 2022-01-28 12:47
Hello @lhuth, 

The version of root installed is 6.24/02.  

thanks, 
@km-b214

**Comment by km-b214** [comment] 2022-01-28 13:15
I updated root to root 6.24/06 but the error message is still the same. 

@km-b214

**Comment by lhuth** [comment] 2022-01-28 13:23
We have only tested with versions up to 6.22 - I'll give it a try and come back to you
Cheers

**Comment by lhuth** [comment] 2022-01-28 14:56
Hi, I could reproduce the issue, which is due to a change in `TDirectory` from root 6.22 to 6.24. Pull request is open

**Comment by lhuth** [comment] 2022-02-04 16:56
Hi @km-b214,

everything should be working now in the master. Could you test it please? If everything is fine we can close this issue

**Comment by km-b214** [comment] 2022-02-04 17:24
Hi @lhuth,

Yes, it's working now. Thank you much. You may close this issue. 

@km-b214

**Closed** 2022-02-04 17:25 UTC
