### ISSUE TITLE
euLog crashes

### ISSUE THREAD

**Issue by RPeschke** [eudaq/eudaq#132] opened 2015-05-05 13:42 UTC
Checkout new branch v1.4dev. Try to run it with the GUI LogCollector gave the the following error:

telescope-admin@tb-datura:~/eudaq$ ./STARTRUN.default 
STARTING DAQ
    Cleaning up first...
    Making sure all data files are properly writeprotected
chmod: cannot access 'data/run*.raw': No such file or directory
    ...Done!
    Starting Subprocesses
        RunControl
DEBUG: listenaddress=tcp://192.168.3.1:44000
        LogCollector
Connect:    (waiting) (192.168.3.1:39571)
###### listenaddress=tcp://192.168.3.1:44002
       logfile=../logs/2015-05-05.log
LogServer responded: tcp://192.168.3.1:44002
INFO: Connection from RunControl (192.168.3.1:36086) 2015-05-05 15:39:00.590
Error: Uncaught exception: Unable to lock mutex
  From /home/telescope-admin/eudaq/main/lib/src/Mutex.cc:42
  In eudaq::MutexLock::MutexLock(eudaq::Mutex&, bool)
LogThread is dying...
        DataCollector
Connect:    (waiting) (192.168.3.1:39576)
New default DataCollector with name '' is connecting
DataServer responded: RunNumber = 1
DataServer responded: full server address determined to be  = 'tcp://192.168.3.1:44001'
/home/telescope-admin/eudaq
	 ...Done!
START OF DAQ COMPLETE
telescope-admin@tb-datura:~/eudaq$ Command Thread exiting due to exception:
No response from LogCollector server
  From /home/telescope-admin/eudaq/main/lib/src/LogSender.cc:24
  In void eudaq::LogSender::Connect(const string&, const string&, const string&)

**Comment by TCThenna** [comment] 2015-05-08 12:09
I think this happens when euLog is still running (and is not be killed by ./KILLRUN script). 
Please run ps aux | grep ... and kill remaining eudaq related processes.

And maybe upgrade to 1.4.5 ?

**Comment by simonspa** [comment] 2015-05-13 11:09
@RPeschke could you please check @TCThenna's comment and report a bit more in detail what happens? Check with `ps -ax` that no LogCollector is running, check that the ports are open etc.

**Comment by dreyling** [comment] 2015-05-19 12:09
we (hendrik and jan) confirm that rocesses are killed. however, the mutex-crash (euLog) remains...

**Comment by simonspa** [comment] 2015-05-22 15:27
We are observing similar things over here at the PSI testbeam. Restarting euLog a second time usually makes it running. As already suspected in private conversations this looks like being a race condition since there is no way to reliably reproduce it. Sometimes after a recompilation of EUDAQ it goes away completely.

I still don't understand completely who tries to access the same resources as the log thread and forces it do die. Would it also be possible for the log thread to not die but just wait until the mutex is unlocked? Maybe with a timeout to not run into some sort of deadlock situation.

However, this definitely needs more investigation since it's a really annoying issue and also creates problems when running with STARTRUN scripts - as almost everyone is...

**Comment by simonspa** [comment] 2015-05-25 15:27
This really seems to be a race condition, and to me it looks like it's the LogCollector itself which emits its own OnConnect message too early. A first test inserting a `eidaq::mSleep(100);` right before the actual `EUDAQ_INFO` log message of euLog's `OnConnect()` seems to solve the problem.

This would also explain why the TestLogCollector was not affected by this race condition.

Please cross-check and close this ticket if it is solved for you.

The patch has been committed to the `v1.5-dev` branch.

**Comment by simonspa** [comment] 2015-05-25 18:11
After some more investigation:

this really seems to cause the exception to be thrown, and the committed fix seems to work fine. 

However, when increasing the sleep to 1000ms we end up in a deadlock situation where TCP packets exceed their timeout and want to log this while the LogCollector is still stuck in the initialization and new log senders are not added to the internal list.

Another optiuon would be to completely remove the EUDAQ_INFO call in OnConnect of euLog.hh. This would eliminate this problem, but also remove the useful information of external producers connecting to the LogCollector.

I guess we should for now stick with this solution but keep in mind that this is a problematic situation.

**Comment by TCThenna** [comment] 2015-05-27 07:18
I agree that the LogCollector should inform the user upon connection of an external producer. Also, users are clearly used to this behaviour. We'll keep an eye on it (and hope that ppl use the test beam log book) such that we are aware of how often this occurs.

**Comment by simonspa** [comment] 2015-05-28 14:55
The delay seems to have solved the problem for now.

I'm still getting QT warnings from the `CheckRegistered()` function, but I don't know how to deal with them - is there any QT wizard around?

```
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```

It's probably unrelated but would be nice to have fixed anyway.

**Comment by TCThenna** [comment] 2015-05-28 15:22
Maybe this is missing:
#include <QMetaType>

and 

typedef QVector<QVector<int> > pos;

as we are calling 
   qRegisterMetaType<QModelIndex>("QModelIndex");
   qRegisterMetaType<eudaq::LogMessage>("eudaq::LogMessage");

http://doc.qt.io/qt-4.8/qmetatype.html
https://forum.qt.io/topic/2826/solved-cross-thread-signal-cannot-queue-arguments-of-type-qvector-qvector-int

but neither me no wizard ...

**Comment by simonspa** [comment] 2015-05-28 21:48
Nope, I also googled already some time ago... ;)

**Closed by simonspa** 2015-05-28 21:49 UTC
